### PR TITLE
Filestorage

### PR DESCRIPTION
**Pull request by hjernkrook**
Classes for handling upload and download from web3.storage, including error handling and a few unit tests. Unit testing has been difficult and finally deprioritized. We have not included unit tests of upload to avoid sending unnecessarily large amounts of data to web3.storage upon each run of the tests. We have also not unit testet downloading files due to difficulties in getting that to work with the CI workflow. Everything has been testet via simple scripts that can be found at the end of fileStorage.js. 
And you can ignore the test*.txt files! They accidentally were pushed, should probably remove them and ignore, but hey

### CODE REVIEW

**Comment by Chrimle** [comment]
Got the path-variable working, but the `npm start` in the root folder simply returns: `Cannot GET /`

The same holds true for the `server` folder, where I get an error upon `npm start`: `Error: Cannot find module '/home/chrimle/Documents/GitHub/Bachelor-thesis-blockchain-for-medical-records/server/server/index.js'`

As if there's a `./` too much in a path somewhere?

(Also, I appreciate the README, but could we be given instructions on how to test run the things you commented out at the end of the `fileStorage`-file?)

**Review by Chrimle — APPROVED** [review]
Great work, nice comments too!

**Review by Ralph-IT — COMMENTED** [review]
Fattar inte exakt vad package-lock.json gör, men känslan är att jag kanske inte måste det.

**Review by Ralph-IT — APPROVED** [review]
Fin kod, bra hänvisat till ställen ni lånat kod från, välkommenterat. Allt som allt, mycket bra.

**Pull request merged**
