### PR TITLE
Web3Storage: Parsing & Displaying in Frontend

### PR DESCRIPTION
**Pull request by Chrimle**
# The frontend can now submit new data, and fetch existing data and display it in the frontend

### NewEntryScreen:
NewEntryScreen's helper-method (EHRService) now parses downloaded prescriptions and diagnoses - to then merge with the new ones.
The old EHR-files will remain encrypted, and will be re-uploaded with the new EHR.

### EHROverview:
Now fetches EHRs, prescriptions and diagnoses from EHRService.
This data is shown in the EHROverviewScreen

### CODE REVIEW

**Comment by Chrimle** [comment]
[EHROverview: Fetch EHR](https://trello.com/c/vwnNQLQW/53-ehroverview-fetch-ehr)

**Comment by Chrimle** [comment]
The Web3Storage uploading-branch #30 has now been approved. This is now ready for review.

**Review by hjernkrook — APPROVED** [review]
Haven't tested, but looks good!

**Comment by Chrimle** [comment]
> 



> Haven't tested, but looks good!

Want me to ask someone else?

**Comment by hjernkrook** [comment]
> > 
> 
> > Haven't tested, but looks good!
> 
> Want me to ask someone else?

No I can run the app if you want to now. Just needed to sort out my own branch first. I'll take a look

**Comment by hjernkrook** [comment]
Works like a charm

**Pull request merged**
