### PR TITLE
Handle EHRs & Permissions

### PR DESCRIPTION
**Pull request by Chrimle**
This PR brings:

- Handles non-existing EHRs, and shows placeholders when fields are empty.
- When doctors upload a new EHR, if the patient does not already have an EHR, it is now handled by skipping the download-procedure.
- Whether or not a doctor has permission to read a patient's EHR is checked on the PatientSearchScreen.

image

### CODE REVIEW

**Review by hjernkrook — APPROVED** [review]
OK, but some general comments that should be looked into later when cleaning up the code:
- hasPermission in chainConnection should probably throw a ChainConnectionError indicating a network error if it ends up in the catch-clause. 
- in ehrSercvice, the part calling connection.hasPermission should probably look out for a ChainConnectionError and display an appropriate message to the user. The same goes for error handling at large in this file (and probably other files). The current way of handling ALL errors the same way (and sometimes not at all really except for logging them) seems like bad practise to me. I've tried to achieve ok error handling in e.g. getRegions, so this may be used as a reference if adding the same structure elsewhere. 

Question:
- is the cid always of length 59? If so, then no problem. Else, the current code may cause problems if IPFS returns cids of length != 59.

**Comment by Chrimle** [comment]
> Error handling
Considering we (I) will refactor the code further in a separate branch, I will have a serious look at it. I avoided that aspect when things were uncertain if they would even work or not.

> CID-length
To my knowledge, CIDs are automatically generated using a hash function, which always returns a string with length equal to 59. NOW, it is entirely possible they could extend the CID with another character, and we would run into problems. I will have a look at this during the refactoring.

**Review by DavidZamanian — APPROVED** [review]
👍

**Comment by hjernkrook** [comment]
> > CID-length
> 
> To my knowledge, CIDs are automatically generated using a hash function, which always returns a string with length equal to 59. NOW, it is entirely possible they could extend the CID with another character, and we would run into problems. I will have a look at this during the refactoring.

If it is this way now then no need to look into it. Thanks for the clarification.

**Pull request merged**
