### PR TITLE
Regions fetched from Firebase

### PR DESCRIPTION
**Pull request by Chrimle**
### Firebase
Added Regions, with ID and name
Added Institutions, with ID, region-ID and name
Added Institution-ID to Doctors

### EHROverview
Regions are no longer placeholders
Regions are fetched from Firebase
NOTE: PermittedRegions remain Placeholders!

### EHRService
Added `getRegions()`, to fetch regions from Firebase and return the list of region names
Added `getPatientRegions( patientID )`, Placeholder-method, intends to fetch permitted regions from the blockchain for a given patient

### PlaceholderValues
Changed `permittedRegions` to include Swedish ÅÄÖ to match with Firebase regions

### CODE REVIEW

**Comment by Chrimle** [comment]
[Add regions and institutions in firebase database](https://trello.com/c/e7DQNuDE/52-add-regions-and-institutions-in-firebase-database)

**Review by hjernkrook — APPROVED** [review]
good, but Norrbotten is a bit off in firefox at least. But no biggie

**Review by DavidZamanian — APPROVED** [review]
Snyggt!

**Comment by Chrimle** [comment]
> good, but Norrbotten is a bit off in firefox at least. But no biggie

Yep, noted: #46 
Will solve that separately

**Pull request merged**
