### PR TITLE
Role-based navigation & functionality

### PR DESCRIPTION
**Pull request by Chrimle**
### New Features:

- The starting page differ between the roles.
- Doctor-specific views are limited to only doctors.
- Roles are assigned immediately upon log-in
- There are no longer sensitive patient data persisting when logging out (or, at least it cannot be seen on log-in)

### CODE REVIEW

**Comment by Chrimle** [comment]
[Decide roles](https://trello.com/c/A3m3n3xb/50-decide-roles)

**Review by hjernkrook — APPROVED** [review]
Looks good. I am just wondering if perhaps logIn() in Header.js should throw an error if the role is neither doctor nor patient, instead of just navigating to login, but I am not sure I completely understand how it is used. I think it is fine either way, not too important.

**Review by DavidZamanian — APPROVED** [review]
Bra!

**Comment by Chrimle** [comment]
> Looks good. I am just wondering if perhaps logIn() in Header.js should throw an error if the role is neither doctor nor patient, instead of just navigating to login, but I am not sure I completely understand how it is used. I think it is fine either way, not too important.

Users that are not logged in do not have an assigned `role`, hence why they are redirected to 'Login'. Right now we only have two roles, and plan to keep it that way. Even better would be to have an 'admin' `boolean` to dictate what is accessible and what isn't. But that seems out-of-scope as of right now.

**Pull request merged**
