### PR TITLE
NewEntryScreen uploads to Web3Storage

### PR DESCRIPTION
**Pull request by Chrimle**
# Enables the `NewEntryScreen` to upload files to Web3Storage.

## **Added**:
- **EhrEntry** class was "moved" to the client side.
- **EHRService** acts like a helper class to:
  - Construct EHREntry objects
  - Convert these into JSON objects +(prescriptions & diagnoses)
 - **FileService** 
   - Create Files for these 3 JSON objects
   - Downloads a Web3Storage archive
   - Upload files together in a combined archive to Web3Storage
 - **NewEntryScreen**:
   - Now calls on EHRService to upload the user submitted data
   - Shows upload "status": Loading, error or Success
 - **Overall**:
   - Commented methods using JSDocs
## **Removed**:
- **NewEntryScreen**:
  - No longer create EHR objects (directly)

## Future improvements:
**EHRService** should tell 'FileService' to parse the downloaded files to then merge with new ones
**EHRService** should call on encrypt & decrypt methods
**FileService** should have parsing methods

### CODE REVIEW

**Review by hjernkrook — COMMENTED** [review]
Error handling needs to be added to the uploadFiles function as well as function to retrieve the API token.

**Comment by Chrimle** [comment]
### How to test it quickly:

1. Go to the "Add EHR"-page via the button in the Overview-screen.
2. Open your console (F12) and clear all messages
3. Fill in the data using the input form
4. Press 'submit' and then 'confirm'
5. **NOTE**: Let it take its time, uploading takes only 5 seconds or so.
    For testing purposes, we download these same files to prove the upload was successful.
    This step takes quite long because it may fail on the first attempt to fetch it.
    WE know about their existence, but they may not be distributed on IPFS yet.
6. Take a look at the log. There you should find the 3 files and their content.


image

**Review by hjernkrook — COMMENTED** [review]
• fetchFileContentError class should be capitalized.
• getPatientData should maybe be renamed to getEHR(cid) ? Patient data may also be in the database to this is maybe a bit ambiguous. 
• inconsistent use of ; but maybe not the most important thing (I prefer to use it)
• does fetchEHRContents(cid) really return array of EHR objects on the form (name, content)? Isn't it just an array of File objects?
• EHRService still only uploads the files just created, but I guess this is intended to change to use all file previously fetched as well. 

Overall good work, just wanted to post my thoughts so far!

**Comment by Chrimle** [comment]
Comments above have been addressed.

>  EHRService still only uploads the files just created, but I guess this is intended to change to use all file previously fetched as well.

Well, currently we download the newly created and uploaded files - to make sure it worked (and that fetching files work).
Eventually, it should download some other directory. And EHRService should merge those with the new files (or simply "append").

**Comment by Chrimle** [comment]
[Upload EHR via Frontend](https://trello.com/c/QZYhSJDY/44-upload-ehr-via-frontend)

**Review by hjernkrook — APPROVED** [review]
Works really well for me on Firefox now. The cid works immediately when inspecting on web3.storage and the ipfs url. Love the added touch with the redirection after submission. Great work!

**Review by DavidZamanian — APPROVED** [review]
Works great! Good job :)

**Review by Edenia97 — APPROVED** [review]
Works great in Chrome! A thought is that the user would stay in the Patient Overview page after adding an entry instead of redirecting back to Patient Search view.  
It didn't work as well for Safari. I could not write in the patient ID text field, tried several times and it just worked once. That one time I got an error when trying to add an entry.

**Comment by Chrimle** [comment]
> Works great in Chrome! A thought is that the user would stay in the Patient Overview page after adding an entry instead of redirecting back to Patient Search view. It didn't work as well for Safari. I could not write in the patient ID text field, tried several times and it just worked once. That one time I got an error when trying to add an entry.

Okay, that's great news! Regarding the Safari-bug with the patientID text field, I've submitted a potential fix for that here: #37

**Review by Wendaaj — APPROVED** [review]

**Review by Ralph-IT — APPROVED** [review]
:+1:

**Pull request merged**
