### PR TITLE
Patient change contact info

### PR DESCRIPTION
**Pull request by Chrimle**
### Patients can now edit their contact information!*
 _*: Only email, address and phone number - these are not validated at all before submitting to Firebase._

### CODE REVIEW

**Comment by Chrimle** [comment]
_Now includes an error message, and **really** basic input validation ( not null)!_

**Comment by Chrimle** [comment]
[Allow users to change Contact information](https://trello.com/c/FQUttQJN/47-allow-users-to-change-contact-information)

**Review by DavidZamanian — APPROVED** [review]
Snyggt!

**Review by hjernkrook — APPROVED** [review]
OK

**Pull request merged**
